[package]
name = "libchessticot"
version = "0.1.0"
edition = "2021"
description = "A chess library with engines"
repository = "https://github.com/Simisticot/libchessticot"

[dependencies]
rand = { version = "0.9.0", optional = true }

[features]
rng = ["dep:rand"]
